app = "lazi-api"
primary_region = "syd"
kill_timeout = 180

[build]
  dockerfile = "Dockerfile"

[deploy]
  strategy = "rolling"
  max_unavailable = 1
  wait_timeout = "5m"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  [http_service.concurrency]
    type = "requests"
    soft_limit = 20
    hard_limit = 25

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"

[[services]]
  internal_port = 80
  protocol = "tcp"
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    handlers = ["http"]
    port = 80
    force_https = true  # optional
